finalyear_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('inventory/', include('inventory.urls')),
]

inventory/urls.py
from unicodedata import name
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'inventory'

urlpatterns = [

    path('sensor_data/', views.sensor_data, name='sensor_data'),

    path('', views.item_list, name='item_list'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('item/create/', views.item_create, name='item_create'),
    path('item/<int:pk>/update/', views.item_update, name='item_update'),
    path('item/<int:pk>/delete/', views.item_delete, name='item_delete'),

    path('generate-qr/<int:item_id>/', views.generate_qr, name='generate_qr'),

    path('view_images/', views.view_images, name='view_images'),
    path('delete_image/<str:image_name>/', views.delete_image, name='delete_image'),
    path('hide_image/<str:image_name>/', views.hide_image, name='hide_image'),
    path('show_all_images/', views.show_all_images, name='show_all_images'),

    path('scan_qr_codes/', views.display_qr_content, name='scan_qr_codes'),
    path('receive_checked_values/', views.receive_checked_values, name='receive_checked_values'),

     # URL for listing all scanned items
    path('itemsscanned/', views.item_list, name='item-list'),
    # URL for viewing details of a single scanned item
    path('itemsscanned/<int:pk>/', views.item_detail, name='item-detail'),
    # URL for creating a new scanned item
    path('itemsscanned/create/', views.item_create, name='item-create'),
    # URL for updating details of an existing scanned item
    path('itemsscanned/<int:pk>/update/', views.item_update, name='item-update'),
    # URL for confirming deletion of an existing scanned item
    path('itemsscanned/<int:pk>/delete/', views.item_delete, name='item-delete'),
    # URL for filtering scanned items (optional)
    path('itemsscanned/filter/', views.item_filter, name='item-filter'),

    path('analytics/', views.graph_view, name='analytics'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from unicodedata import name
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.base, name='base'),
    path('about/', views.about, name='about'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashvalues/', views.dashvalues, name='dashvalues'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # password change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),

    # user registration
    path('register/', views.register, name='register'),

    # profile
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('delete-account/', views.delete_account, name='delete_account'),

    # contact
    path('contact/', views.contact, name='contact'),

    # review
    path('add_review/<int:consumer_id>/', views.add_review, name='add_review'),
    path('view_reviews/<int:consumer_id>/', views.view_reviews, name='view_reviews'),

    # notification
    path('notifications/', views.user_notifications, name='user_notifications'),

    #email
    path('send_email/', views.send_email, name='send_email'),

    #chat
    path('chat/', views.chat, name='chat'),

    path('sensor_data/', views.sensor_data, name='sensor_data'),

    path('item_list', views.item_list, name='item_list'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('item/create/', views.item_create, name='item_create'),
    path('item/<int:pk>/update/', views.item_update, name='item_update'),
    path('item/<int:pk>/delete/', views.item_delete, name='item_delete'),

    path('generate-qr/<int:item_id>/', views.generate_qr, name='generate_qr'),

    path('generate_notification/', views.generate_notification, name='generate_notification'),
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/navigation/navigation3.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
            <!-- <li class="nav-item mr-3"> 
                <a class="nav-link text-dark" href="{% url 'about' %}">About</a>
            </li> -->
            <li class="nav-item mr-3"> 
                <a class="nav-link text-dark" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'item_list' %}">Add Products</a>
            </li>

            <li class="nav-item mr-3"> 
                <a class="nav-link text-dark" href="{% url 'inventory:view_images' %}">View QR</a>
            </li>

            <li class="nav-item mr-3"> 
                <a class="nav-link text-dark" href="{% url 'inventory:scan_qr_codes' %}">Scan QR</a>
            </li>

            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'user_notifications' %}">Notification</a>
            </li>

            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'inventory:item-list' %}">Scanned Items</a>
            </li>

            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'inventory:analytics' %}">Visualization</a>
            </li>
            
            <form method="post" action="{% url 'logout' %}" class="form-inline mb-2" style="text-align: right;">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-success ">Logout</button>
            </form>
            

        {% else %}
            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item mr-3"> <!-- Added margin -->
                <a class="nav-link text-dark" href="{% url 'register' %}">Register</a>
            </li>
        {% endif %}
      </ul>
    </div>
</nav>