finalyear_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('inventory/', include('inventory.urls')),
]

inventory/urls.py
from unicodedata import name
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'inventory'

urlpatterns = [

    path('sensor_data/', views.sensor_data, name='sensor_data'),

    path('', views.item_list, name='item_list'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('item/create/', views.item_create, name='item_create'),
    path('item/<int:pk>/update/', views.item_update, name='item_update'),
    path('item/<int:pk>/delete/', views.item_delete, name='item_delete'),

    path('generate-qr/<int:item_id>/', views.generate_qr, name='generate_qr'),

    path('view_images/', views.view_images, name='view_images'),
    path('delete_image/<str:image_name>/', views.delete_image, name='delete_image'),
    path('hide_image/<str:image_name>/', views.hide_image, name='hide_image'),
    path('show_all_images/', views.show_all_images, name='show_all_images'),

    path('scan_qr_codes/', views.display_qr_content, name='scan_qr_codes'),
    path('receive_checked_values/', views.receive_checked_values, name='receive_checked_values'),

     # URL for listing all scanned items
    path('itemsscanned/', views.item_list, name='item-list'),
    # URL for viewing details of a single scanned item
    path('itemsscanned/<int:pk>/', views.item_detail, name='item-detail'),
    # URL for creating a new scanned item
    path('itemsscanned/create/', views.item_create, name='item-create'),
    # URL for updating details of an existing scanned item
    path('itemsscanned/<int:pk>/update/', views.item_update, name='item-update'),
    # URL for confirming deletion of an existing scanned item
    path('itemsscanned/<int:pk>/delete/', views.item_delete, name='item-delete'),
    # URL for filtering scanned items (optional)
    path('itemsscanned/filter/', views.item_filter, name='item-filter'),

    path('analytics/', views.graph_view, name='analytics'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from unicodedata import name
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.base, name='base'),
    path('about/', views.about, name='about'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashvalues/', views.dashvalues, name='dashvalues'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # password change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),

    # user registration
    path('register/', views.register, name='register'),

    # profile
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('delete-account/', views.delete_account, name='delete_account'),

    # contact
    path('contact/', views.contact, name='contact'),

    # review
    path('add_review/<int:consumer_id>/', views.add_review, name='add_review'),
    path('view_reviews/<int:consumer_id>/', views.view_reviews, name='view_reviews'),

    # notification
    path('notifications/', views.user_notifications, name='user_notifications'),

    #email
    path('send_email/', views.send_email, name='send_email'),

    #chat
    path('chat/', views.chat, name='chat'),

    path('sensor_data/', views.sensor_data, name='sensor_data'),

    path('item_list', views.item_list, name='item_list'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('item/create/', views.item_create, name='item_create'),
    path('item/<int:pk>/update/', views.item_update, name='item_update'),
    path('item/<int:pk>/delete/', views.item_delete, name='item_delete'),

    path('generate-qr/<int:item_id>/', views.generate_qr, name='generate_qr'),

    path('generate_notification/', views.generate_notification, name='generate_notification'),
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
# models.py
from django.db import models

class Item(models.Model):
    ITEM_CLASSES = (
        ('electronic', 'Electronic'),
        ('chemical', 'Chemical'),
        ('books', 'Books'),
        ('clothing', 'Clothing'),
        ('food', 'Food'),
        ('other', 'Other'),
    )

    name = models.CharField(max_length=100)
    units = models.IntegerField()
    fragile = models.BooleanField(default=False)
    weight = models.DecimalField(max_digits=10, decimal_places=2)
    unit_choices = models.CharField(max_length=20, choices=(('grams', 'grams'), ('kilos', 'kilos'), ('tonnes', 'tonnes')))
    item_class = models.CharField(max_length=20, choices=ITEM_CLASSES)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    units = models.IntegerField(default=0)
    fragile = models.BooleanField(default=False)
    weight = models.FloatField(default=0)
    unit = models.CharField(max_length=50)
    item_class = models.CharField(max_length=50)

    def __str__(self):
        return self.name

from django.utils import timezone

class scannedItems(models.Model):
    name = models.CharField(max_length=100)
    units = models.IntegerField(default=0)
    fragile = models.BooleanField(default=False)
    weight = models.FloatField(default=0)
    unit = models.CharField(max_length=50)
    item_class = models.CharField(max_length=50)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

inventory/forms.py

# forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'units', 'fragile', 'weight', 'unit_choices', 'item_class']

from .models import scannedItems

class ScannedItemForm(forms.ModelForm):
    class Meta:
        model = scannedItems
        fields = ['name', 'units', 'fragile', 'weight', 'unit', 'item_class']

inventory/views.py
from django.shortcuts import render
import serial
import time
from django.http import HttpResponse
from inventory.models import Item
from inventory.forms import ItemForm
import qrcode
from PIL import Image

def sensor_data(request):
    # Replace 'COM6' with your Arduino's serial port
    serial_port = 'COM4'
    baud_rate = 9600

    try:
        # Establish serial connection
        ser = serial.Serial(serial_port, baud_rate)

        # Read data from Arduino
        data = ser.readline().decode('latin-1').strip()

        # Close serial connection
        ser.close()

        # Pass the data to the template
        return render(request, 'sensor_val.html', {'data': data})
    except serial.SerialException:
        # Handle serial port error
        return HttpResponse("Error: Serial port not available or accessible.")

# views.py
from django.shortcuts import render, redirect, get_object_or_404


def item_list(request):
    items = Item.objects.all()
    return render(request, 'item_list.html', {'items': items})

def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'item_detail.html', {'item': item})

def item_create(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save()
            return redirect('item_detail', pk=item.pk)
    else:
        form = ItemForm()
    return render(request, 'item_form.html', {'form': form})

def item_update(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save()
            return redirect('item_detail', pk=item.pk)
    else:
        form = ItemForm(instance=item)
    return render(request, 'item_form.html', {'form': form})

def item_delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('item_list')
    return render(request, 'item_confirm_delete.html', {'item': item})


# ----------------------------------------------------------------

# generate QR
import qrcode
from PIL import Image, ImageDraw
import os
import random

def generate_random_color():
    # Generate random RGB values
    r = random.randint(0, 255)
    g = random.randint(0, 255)
    b = random.randint(0, 255)
    
    # Format RGB values into a tuple
    return (r, g, b)

def generate_qr_code(item):
    # Generate a random color for the QR code
    color = generate_random_color()
    
    # Format data into a string
    data = f"Name: {item.name}\nUnits: {item.units}\nFragile: {'Yes' if item.fragile else 'No'}\nWeight: {item.weight}\nUnit Choices: {item.unit_choices}\nItem Class: {item.item_class}"
    
    # Generate QR code
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)
    
    # Create an image from the QR code
    img = qr.make_image(fill_color="black", back_color="white")

    # Convert the image to RGBA mode to support transparency
    img = img.convert("RGBA")
    
    # Create a drawing context
    draw = ImageDraw.Draw(img)

    # Overlay the QR code with the chosen color
    width, height = img.size
    for x in range(width):
        for y in range(height):
            pixel_color = img.getpixel((x, y))
            if pixel_color == (0, 0, 0, 255):  # Black pixels in the QR code
                draw.point((x, y), fill=color)  # Overlay with the chosen color

    # Specify the file path within the static/qr folder
    file_path = f"static/qr/{item.name}_qr_code.png"
    
    # Save the QR code image
    img.save(file_path)

def generate_qr(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    
    # Generate QR code with a random color for the item
    generate_qr_code(item)
    
    return redirect('inventory:view_images')


# ----------------------------------------------------------------

#  display images on frontend
from django.shortcuts import render, redirect
import os

mode_path = r'static/qr/'

def view_images(request):
    # Get a list of all image files in the folder
    image_files = [f for f in os.listdir(mode_path) if os.path.isfile(os.path.join(mode_path, f))]
    
    # Render the HTML template with the list of image files
    return render(request, 'view_images.html', {'image_files': image_files})

def delete_image(request, image_name):
    # Get the path to the image file
    image_path = os.path.join(mode_path, image_name)
    
    # Check if the file exists
    if os.path.exists(image_path):
        # Delete the file
        os.remove(image_path)
    
    # Redirect back to the view_images view
    return redirect('inventory:view_images')

def hide_image(request, image_name):
    # Your code to hide the image
    # For example, you can move the image to a hidden folder
    source_path = os.path.join(mode_path, image_name)
    hidden_folder = os.path.join(mode_path, 'hidden')
    destination_path = os.path.join(hidden_folder, image_name)

    # Create the hidden folder if it doesn't exist
    if not os.path.exists(hidden_folder):
        os.makedirs(hidden_folder)
    
    # Move the image to the hidden folder
    os.rename(source_path, destination_path)
    
    # Redirect back to the view_images view
    return redirect('inventory:view_images')

def show_all_images(request):
    # Your code to show all images (if they were hidden)
    # For example, you can move all images from the hidden folder back to the main folder
    hidden_folder = os.path.join(mode_path, 'hidden')

    # Check if the hidden folder exists
    if os.path.exists(hidden_folder):
        for image_name in os.listdir(hidden_folder):
            source_path = os.path.join(hidden_folder, image_name)
            destination_path = os.path.join(mode_path, image_name)
            
            # Move the image back to the main folder
            os.rename(source_path, destination_path)
    
    # Redirect back to the view_images view
    return redirect('inventory:view_images')


# scan and update qr
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product

# views.py

from django.shortcuts import render
from django.http import JsonResponse

def display_qr_content(request):
    if request.method == 'POST':
        qr_content = request.POST.get('qr_content', '')
        return JsonResponse({'qr_content': qr_content})
    else:
        return render(request, 'scan_qr.html')

# ----------------------------------------------------------------
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import scannedItems  # Import your model

@csrf_exempt
def receive_checked_values(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            checked_values = data.get('checked_values', [])
            
            # Process the received values and save them to the database
            for value in checked_values:
                # Split the value into fields
                fields = value.split('\n')
                
                # Extract field values
                name = fields[0].split(': ')[1]
                units = int(fields[1].split(': ')[1])
                fragile = fields[2].split(': ')[1] == 'Yes'
                weight = float(fields[3].split(': ')[1])
                unit = fields[4].split(': ')[1]
                item_class = fields[5].split(': ')[1]
                
                # Create and save the scanned item
                scanned_item = scannedItems(
                    name=name,
                    units=units,
                    fragile=fragile,
                    weight=weight,
                    unit=unit,
                    item_class=item_class
                )
                scanned_item.save()
                
            return JsonResponse({'message': 'Values received and saved successfully'}, status=200)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON data'}, status=400)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=405)

# ----------------------------------------------------------------
# views.py

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import scannedItems
from .forms import ScannedItemForm

def item_list(request):
    items = scannedItems.objects.all()
    return render(request, 'crud/list_items.html', {'items': items})

def item_detail(request, pk):
    item = get_object_or_404(scannedItems, pk=pk)
    return render(request, 'crud/item_detail.html', {'item': item})

def item_create(request):
    if request.method == 'POST':
        form = ScannedItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('item-list')
    else:
        form = ScannedItemForm()
    return render(request, 'crud/item_form.html', {'form': form})

def item_update(request, pk):
    item = get_object_or_404(scannedItems, pk=pk)
    if request.method == 'POST':
        form = ScannedItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item-list')
    else:
        form = ScannedItemForm(instance=item)
    return render(request, 'crud/item_form.html', {'form': form})

def item_delete(request, pk):
    item = get_object_or_404(scannedItems, pk=pk)
    if request.method == 'POST':

inventory/templates/analytics.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block style %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{% endblock %}
{% load static %}
{% block index %}
{% endblock %}

{% block content %}
    <canvas id="myChart" width="50" height="20"></canvas>

    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['Fragile', 'Non-Fragile'],
                datasets: [{
                    label: 'Item Count',
                    data: [{{ fragile_count }}, {{ non_fragile_count }}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
{% endblock %}

inventory/templates/item_confirm_delete.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block style %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Vehicle</title>
    <!-- Include Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

{% endblock %}
{% block index %}
{% endblock %}

{% block content %}

{% endblock %}

inventory/templates/item_detail.html
{% extends "base.html" %}
{% block title %}Notifications{% endblock %}
{% block style %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Vehicle</title>
    <!-- Include Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

{% endblock %}
{% block index %}
{% endblock %}

{% block content %}

<div class="container">
    <h1>Item Detail</h1>
    <div class="row">
        <div class="col s12 m6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ item.name }}</span>
                    <p><strong>Units:</strong> {{ item.units }}</p>
                    <p><strong>Fragile:</strong> {{ item.fragile }}</p>
                    <p><strong>Weight:</strong> {{ item.weight }}</p>
                    <p><strong>Unit:</strong> {{ item.unit_choices }}</p>
                    <p><strong>Class:</strong> {{ item.item_class }}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'item_update' item.pk %}" class="waves-effect waves-light btn">Update</a>
                    <form action="{% url 'item_delete' item.pk %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="waves-effect waves-light btn red darken-3">Delete</button>
                    </form>
                    <a href="{% url 'item_list' %}" class="waves-effect waves-light btn">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

{% endblock %}

inventory/templates/item_form.html
{% extends "base.html" %}
{% block title %}Notifications{% endblock %}
{% block style %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Vehicle</title>
    <!-- Include Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

{% endblock %}
{% block index %}
{% endblock %}

{% block content %}

<div class="container">
    <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Item</h1>
    <div class="row">
        <form class="col s12" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s6">
                    {{ form.name.label_tag }}
                    {{ form.name }}
                </div>
                <div class="input-field col s6">
                    {{ form.units.label_tag }}
                    {{ form.units }}
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <label>
                        <input type="checkbox" name="{{ form.fragile.name }}" class="filled-in" {% if form.fragile.value %}checked{% endif %}>
                        <span>{{ form.fragile.label }}</span>
                    </label>
                </div>
                <div class="input-field col s6">
                    {{ form.weight.label_tag }}
                    {{ form.weight }}
                </div>
            </div>
            
            
            <div class="row">
                <div class="input-field col s6">
                    {{ form.unit_choices.label_tag }}
                    <select name="unit_choices">
                        {% for choice in form.unit_choices.field.choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-field col s6">
                    {{ form.item_class.label_tag }}
                    <select name="item_class">
                        {% for choice in form.item_class.field.choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button class="btn waves-effect waves-light" type="submit">{% if form.instance.pk %}Update{% else %}Create{% endif %}
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
    });
</script>
{% endblock %}

inventory/templates/item_list.html
{% extends "base.html" %}
{% block title %}Item List{% endblock %}
{% block style %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Vehicle</title>
    <!-- Include Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
{% endblock %}
{% block index %}
{% endblock %}
{% block content %}
<div class="container">
    <h1>Item List</h1>
    <table class="striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Units</th>
                <th>Fragile</th>
                <th>Weight</th>
                <th>Unit</th>
                <th>Class</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.units }}</td>
                <td>{{ item.fragile }}</td>
                <td>{{ item.weight }}</td>
                <td>{{ item.unit_choices }}</td>
                <td>{{ item.item_class }}</td>
                <td>
                    <a href="{% url 'item_detail' item.pk %}" class="waves-effect waves-light btn">Detail</a>
                    <a href="{% url 'item_update' item.pk %}" class="waves-effect waves-light btn">Update</a>
                    <form action="{% url 'item_delete' item.pk %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="waves-effect waves-light btn red darken-3">Delete</button>
                    </form>
                    <a href="{% url 'generate_qr' item.pk %}" class="waves-effect waves-light btn">Generate QR</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'item_create' %}" class="waves-effect waves-light btn">Create New Item</a>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
{% endblock %}

inventory/templates/scanned_products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scanned Products</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Scanned Products</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Units</th>
            <th>Fragile</th>
            <th>Weight</th>
            <th>Unit</th>
            <th>Item Class</th>
        </tr>
        {% for product in scanned_products %}
        <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.units }}</td>
            <td>{{ "Yes" if product.fragile else "No" }}</td>
            <td>{{ product.weight }}</td>
            <td>{{ product.unit }}</td>
            <td>{{ product.item_class }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

inventory/templates/sensor_val.html
{% extends "base.html" %}
{% block title %}Notifications{% endblock %}
{% block style %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Vehicle</title>
    <!-- Include Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

{% endblock %}
{% block index %}
{% endblock %}

{% block content %}
    <h1>Arduino Data</h1>
    <p>The fetched data from Arduino is: {{ data }}</p>
{% endblock %}

inventory/templates/view_images.html
{% extends "base.html" %}
{% block title %}View QR{% endblock %}
{% block style %}
    <style>
        /* Optional: Add some basic styling */
        ul {
            list-style-type: none;
            padding: 0;
            overflow-x: auto; /* Add horizontal scrolling if needed */
            white-space: nowrap; /* Ensure images stay in a single line */
        }
        li {
            display: inline-block;
            margin-right: 20px;
            vertical-align: top; /* Align images to the top */
        }
        img {
            margin-right: 10px;
            vertical-align: middle;
        }
        .actions {
            margin-left: 10px;
        }
    </style>
{% endblock %}
{% block index %}
{% endblock %}
{% block content %}
<center>
    <h1>Images</h1>
    <ul>
        {% for image_file in image_files %}
        <li>
            <span>{{ image_file }}</span><br>
            <img src="/static/qr/{{ image_file }}" alt="{{ image_file }}" height="100">
            
            <div class="actions">
                <a href="{% url 'inventory:delete_image' image_file %}">Delete</a>
                <a href="{% url 'inventory:hide_image' image_file %}">Hide</a>
            </div>
        </li>        
        {% endfor %}
    </ul>
    <a href="{% url 'inventory:show_all_images' %}">Show All Images</a>
</center>
{% endblock %}